import { usesHusky } from '../package.json.js';
import { astroCommand, runScript } from '../../../package-manager.js';
import type { ProjectInput } from '../../../types.js';

export const path = '.github/SUPPORT.md';

const packageManagerDocs: Record<
  ProjectInput['packageManager'],
  [string, string]
> = {
  pnpm: ['pnpm', 'https://pnpm.io/docs'],
  npm: ['npm', 'https://docs.npmjs.com'],
  yarn: ['Yarn', 'https://yarnpkg.com/docs'],
  bun: ['Bun', 'https://bun.sh/docs'],
};

function docs(input: ProjectInput): Array<[string, string]> {
  const links: Array<[string, string]> = [
    ['Astro', 'https://docs.astro.build'],
  ];
  if (input.improvements.eminenceAstroSuite)
    links.push([
      'eminence-astro-suite',
      'https://eminence-astro-suite.xeffen25.com',
    ]);
  links.push(
    ['Cloudflare Workers', 'https://developers.cloudflare.com/workers/'],
    ['Wrangler', 'https://developers.cloudflare.com/workers/wrangler/'],
    ['Cloudflare general platform docs', 'https://developers.cloudflare.com'],
  );
  if (input.frameworks.includes('svelte'))
    links.push(['Svelte', 'https://svelte.dev/docs/svelte/overview']);
  if (input.frameworks.includes('react'))
    links.push(['React', 'https://react.dev/reference/react']);
  if (input.improvements.tailwind)
    links.push([
      'Tailwind CSS',
      'https://tailwindcss.com/docs/installation/using-vite',
    ]);
  if (input.language.paraglide)
    links.push(
      [
        'Paraglide JS',
        'https://inlang.com/m/gerre34r/library-inlang-paraglideJs',
      ],
      ['inlang CLI', 'https://inlang.com/m/r7kp499g/app-inlang-ide'],
    );
  if (input.improvements.vitest)
    links.push(['Vitest', 'https://vitest.dev/guide/']);
  links.push([
    '@astrojs/check',
    'https://docs.astro.build/en/guides/typescript/#astro-check',
  ]);
  if (input.frameworks.includes('svelte'))
    links.push([
      '@astrojs/svelte',
      'https://docs.astro.build/en/guides/integrations-guide/svelte/',
    ]);
  if (input.frameworks.includes('react'))
    links.push([
      '@astrojs/react',
      'https://docs.astro.build/en/guides/integrations-guide/react/',
    ]);
  links.push([
    '@astrojs/cloudflare',
    'https://docs.astro.build/en/guides/integrations-guide/cloudflare/',
  ]);
  if (input.improvements.sitemap)
    links.push([
      '@astrojs/sitemap',
      'https://docs.astro.build/en/guides/integrations-guide/sitemap/',
    ]);
  if (input.improvements.resend)
    links.push(['Resend', 'https://resend.com/docs']);
  links.push(
    ['TypeScript', 'https://www.typescriptlang.org/docs/'],
    ['Node.js', 'https://nodejs.org/docs/latest-v24.x/api/'],
    packageManagerDocs[input.packageManager],
  );
  if (input.improvements.prettier) {
    links.push(
      ['Prettier', 'https://prettier.io/docs/en/'],
      [
        'prettier-plugin-astro',
        'https://github.com/withastro/prettier-plugin-astro',
      ],
    );
    if (input.frameworks.includes('svelte'))
      links.push([
        'prettier-plugin-svelte',
        'https://github.com/sveltejs/prettier-plugin-svelte',
      ]);
  }
  if (usesHusky(input)) {
    links.push(['Husky', 'https://typicode.github.io/husky/']);
    if (input.improvements.prettier)
      links.push(['Lint-staged', 'https://github.com/okonet/lint-staged']);
  }
  links.push(['Sharp', 'https://sharp.pixelplumbing.com/']);
  return links;
}

function troubleshooting(input: ProjectInput): string[] {
  const run = (script: string) => runScript(input.packageManager, script);
  const install =
    input.packageManager === 'npm'
      ? 'npm install'
      : `${input.packageManager} install`;
  const steps = [
    "**Check the Wiki:** Ensure you aren't missing a project-specific step.",
    `**Clean Install:** Try running \`${install}\` again to ensure dependencies are synced.`,
  ];
  const regenerate: string[] = [
    `If Worker bindings look stale, run \`${run('generate-types')}\`.`,
  ];
  if (input.language.paraglide)
    regenerate.push(
      'Paraglide output is regenerated by `astro dev` / `astro build`.',
    );
  if (regenerate.length)
    steps.push(`**Regenerate generated files:** ${regenerate.join(' ')}`);
  const checks = [
    `\`${run('github:ci')}\` for the standard validation flow`,
    `\`${astroCommand(input.packageManager, 'check')}\``,
    ...(input.improvements.vitest ? [`\`${run('test')}\``] : []),
    `\`${run('build')}\``,
  ];
  steps.push(
    `**Run the project checks:** Use ${checks[0]}, or run ${checks.slice(1).join(', ')} individually to isolate the failure.`,
  );
  if (usesHusky(input) && input.improvements.prettier)
    steps.push(
      '**Verify Git Hooks:** If your commit is failing, ensure your code passes the Prettier rules enforced by **Husky** and **Lint-staged**.',
    );
  steps.push(
    '**Search Issues:** Check both open and closed issues in this repository.',
  );
  return steps.map((step, index) => `${index + 1}. ${step}`);
}

export function generate(input: ProjectInput): string {
  const wikiUses = [
    '- Step-by-step setup guides.',
    '- Understanding how we handle Astro integrations.',
    '- Nuances regarding our Cloudflare deployment flow.',
  ];
  const help = [
    input.improvements.issueTemplates
      ? '- **Bug/Feature:** Open a new issue using the appropriate template.'
      : '- **Bug/Feature:** Open a new issue.',
  ];
  return `# 🛠️ Support & Documentation

Before opening an issue or asking for help, please follow this guide to find the information you need. Our goal is to keep the issue tracker focused on actionable development tasks.

---

## 📖 1. Project Wiki (Primary Resource)

For detailed tutorials, architectural overviews, and integration nuances specific to this stack, please visit this repository's **GitHub Wiki**.

**Use the Wiki for:**

${wikiUses.join('\n')}

---

## 📚 2. Official Technical Documentation

If your question is about a specific technology we use, the official docs are the fastest way to get an answer. We use the following stack (ordered by relevance):

${docs(input)
  .map(([name, url]) => `- [${name}](${url})`)
  .join('\n')}

---

## 🔍 3. Troubleshooting Workflow

If you encounter an error during development:

${troubleshooting(input).join('\n')}

---

## ✉️ Still Need Help?

If you've exhausted the resources above:

${help.join('\n')}
`;
}
